base_url = "https://blanc.pages.dev"
title = "Filling the Void"

compile_sass = true

taxonomies = [
    {name = "tags"}
]

[markdown]
highlight_code = true
highlight_theme = "ayu-dark"

[extra]
# One of: blue, green, orange, pink, red.
accent_color = "blue"

# One of: blue, dark, green, orange, pink, red.
background_color = "blue"

logo_text = "Lily is Here"

author = "Lily"

menu_items = [
    {name = "Blog", url = "$BASE_URL"},
    {name = "About", url = "$BASE_URL/about"},
    {name = "Tags", url = "$BASE_URL/tags"},
    {name = "Archive", url = "$BASE_URL/archive"},
]

enable_post_view_navigation = true

post_view_navigation_prompt = "Thanks for reading this post! You can read other posts too!"

use_full_hack_font = false

favicon = "/favicon.ico"
favicon_mimetype = "image/x-icon"
